import { validateEnv } from './utils/common';

const ENV = process.env.NEXT_PUBLIC_ENV!;
const OIDC_ISSUER = process.env.NEXT_PUBLIC_OIDC_ISSUER!;
const SEARCH_FULLTEXT_HOST = process.env.NEXT_PUBLIC_SEARCH_FULLTEXT_HOST!;
const REFERENCE_DATA_HOST = process.env.NEXT_PUBLIC_REFERENCE_DATA_HOST!;
const FDK_PORTAL_HOST = process.env.NEXT_PUBLIC_FDK_PORTAL_HOST!;
const CMS_API_HOST = process.env.NEXT_PUBLIC_CMS_API_HOST!;
const COMMUNITY_API_HOST = process.env.NEXT_PUBLIC_COMMUNITY_API_HOST!;
const METADATA_QUALITY_ASSESSMENT_API =
  process.env.NEXT_PUBLIC_METADATA_QUALITY_ASSESSMENT_API!;
const ORGANIZATION_HOST = process.env.NEXT_PUBLIC_ORGANIZATION_HOST!;
const ORGANIZATION_CATALOGUE_HOST =
  process.env.NEXT_PUBLIC_ORGANIZATION_CATALOGUE_HOST!;
const REPORT_API_HOST = process.env.NEXT_PUBLIC_REPORT_API_HOST!;
const STRAPI_API_HOST = process.env.NEXT_PUBLIC_STRAPI_API_HOST!;
const FDK_USER_FEEDBACK_SERVICE_BASE_URI =
  process.env.NEXT_PUBLIC_FDK_USER_FEEDBACK_SERVICE_BASE_URI!;
const OIDC_CLIENT_SECRET = process.env.NEXT_PUBLIC_OIDC_CLIENT_SECRET!;
const FDK_DATASET_PREVIEW_API_KEY =
  process.env.NEXT_PUBLIC_FDK_DATASET_PREVIEW_API_KEY!;

const env = {
  ENV,
  OIDC_ISSUER,
  OIDC_CLIENT_SECRET,
  SEARCH_FULLTEXT_HOST,
  REFERENCE_DATA_HOST,
  FDK_PORTAL_HOST,
  CMS_API_HOST,
  COMMUNITY_API_HOST,
  METADATA_QUALITY_ASSESSMENT_API,
  ORGANIZATION_HOST,
  ORGANIZATION_CATALOGUE_HOST,
  REPORT_API_HOST,
  FDK_DATASET_PREVIEW_API_KEY,
  STRAPI_API_HOST,
  FDK_USER_FEEDBACK_SERVICE_BASE_URI
};

export default validateEnv(env);
