export const GET_COMMUNITY_RECENT_TOPICS_REQUESTED =
  'GET_COMMUNITY_RECENT_TOPICS_REQUESTED' as const;
export const GET_COMMUNITY_POPULAR_TOPICS_REQUESTED =
  'GET_COMMUNITY_POPULAR_TOPICS_REQUESTED' as const;
export const GET_COMMUNITY_TOPICS_BY_TAG_REQUESTED =
  'GET_COMMUNITY_TOPICS_BY_TAG_REQUESTED' as const;
export const GET_COMMUNITY_TOPICS_SUCCEEDED =
  'GET_COMMUNITY_TOPICS_SUCCEEDED' as const;
export const GET_COMMUNITY_TOPICS_FAILED =
  'GET_COMMUNITY_TOPICS_FAILED' as const;
export const RESET_COMMUNITY_TOPICS = 'RESET_COMMUNITY_TOPICS' as const;
