name: Deploy to staging

on:
  pull_request:
    types: [ready_for_review, opened, reopened, synchronize]
    branches:
      - main

jobs:
  build-test-and-deploy-staging:
    name: Build and deploy to staging environment on pull request to main branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Auth gcloud CLI for image-store
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_DATAFABRIKKEN_GCR_KEY }}

      - name: Configure docker to use the gcloud command-line tool as a credential helper
        run: gcloud auth configure-docker eu.gcr.io

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: eu.gcr.io/datafabrikken-infra/datafabrikken-portal-nextjs
          flavor: |
            latest=false
          tags: |
            type=raw,value=staging_latest
            type=raw,value=${{ github.sha }},priority=1000
            type=ref,event=branch

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args:  |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            NEXT_PUBLIC_FDK_PORTAL_HOST=https://staging.fellesdatakatalog.digdir.no

      - name: Apply Helm template
        run: |
          helm repo add datafabrikken https://datadeling.github.io/helm-chart/
          helm fetch --untar --untardir ./helm datafabrikken/datafabrikken-portal-nextjs
          helm template  \
            --set DOCKER_IMAGE_NAME="eu.gcr.io/datafabrikken-infra/datafabrikken-portal-nextjs:${{ steps.meta.outputs.version }}" \
            -f ./helm/datafabrikken-portal-nextjs/values/staging.yaml \
            ./helm/datafabrikken-portal-nextjs/ > ./kubectlapply.yaml
          chmod o+w ./kubectlapply.yaml
          cat kubectlapply.yaml

      - name: Auth gcloud CLI for deploy
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.DATAFABRIKKEN_DEV_AUTODEPLOY }}

      - name: Get credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: datafabrikken-dev
          location: europe-north1-a

      - name: Deploy to GCP
        run: |
          kubectl apply -f ./kubectlapply.yaml --force

      - name: Notify slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: 'Application: datafabrikken-portal-nextjs | Environment: staging'
          fields: commit,author,workflow
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
